[workspace]
resolver = "2"
members=[
    "service",
    "knn_rs"
]

[patch.crates-io]
faiss = { git = 'https://github.com/chroussel/faiss-rs.git' }
faiss-sys = { git = 'https://github.com/chroussel/faiss-rs.git' }
