[package]
name = "knn_rs"
version = "0.1.0"
authors = ["Charles Roussel <c.roussel@criteo.com>"]
edition = "2018"
build = "build.rs"

[lib]
bench = false

[dependencies]
libc= "0.2"
ndarray  = "0.13"
failure = "0.1"
parquet = "0.16"
log = "0.4"
tempdir = "0.3"
tensorflow = "0.14.0"
prost = "0.6"
bytes = "0.5"

[build-dependencies]
cc = "1.0"
bindgen = "0.53"
prost-build = "0.6"
curl = "0.4.24"
flate2 = "1.0.12"
pkg-config = "0.3.16"
semver = "0.9.0"
tar = "0.4.26"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "bench"
harness = false
